config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dishes, only: [:index, :show, :new, :create]
  resources :orders, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :dish
  has_many :orders
  validates :portions, presence: true
  validates :available_datetime, presence: true

  def to_s
    available_datetime
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_attachment :photo
  belongs_to :user
  has_many :availabilities
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :availability
  validates :portions, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :photo
  has_many :dishes
  has_many :orders
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :address, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :address])
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:search, :index, :show, :create, :new]

  def index

    @searched_date = params[:search][:date]
    @searched_slot = params[:search][:slot]
    @searched_address = params[:search][:address]
    @searched_portions = params[:search][:portions].to_i
    @searched_types = params[:search][:types]

    if @searched_date.present?
      if @searched_slot == 'Midi'
        @datetime = DateTime.parse(@searched_date +  " 12:00 UTC +00:00")
      elsif @searched_slot == 'Soir'
        @datetime = DateTime.parse(@searched_date +  " 20:00 UTC +00:00")
      end
    end

    @dishes = Dish.joins(:availabilities)
    @dishes = @dishes.where("availabilities.available_datetime = ? ", @datetime) if @datetime
    @dishes = @dishes.where("availabilities.left_portions >= ? ", @searched_portions) if @searched_portions.present?
    @dishes = @dishes.where("dishes.bio = ? ", true) if @searched_types && @searched_types[0].present?
    @dishes = @dishes.where("dishes.gluten_free = ? ", true) if @searched_types && @searched_types[1].present?
    @dishes = @dishes.where("dishes.vegetarian = ? ", true) if @searched_types && @searched_types[2].present?

    @users = []
    portions_results = []
    @dishes.each do |dish|
      @users <<  dish.user  if dish.user.latitude && dish.user.longitude
      dish.availabilities.each do |availability|
        portions_results << availability.left_portions if availability.left_portions > 0
      end
    end
    (portions_results.count > 1) ? @max_results_portions = portions_results.max : @max_results_portions =1

    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
    # if @searched_address
    #   @searched_coordinates = Geocoder.search(@searched_address).first
    #   @searched_hash = Gmaps4rails.build_markers(@searched_coordinates) do |coord, marker|
    #     marker.lat coord[:lat]
    #     marker.lng coord[:lng]
    #   end
    # end
  end

  def show
    # @dish for TEST use only
    @dish = Dish.find(params[:id])
    # @chosen = Dish.find(params[:id]).availabilities.first

    # # replace it with => @dish = Dish.find(dish_params)
    # @chosen_availability = format_datetime(@chosen.available_datetime)
    # #@other = Dish.find(1).availabilities.to_a.delete(chosen)

    # récupérer la date choisie (+ heure du shift)
    @chosen_shift = DateTime.parse(params["shift"])
    # récupérer l'id de l'availablitytzgeufojze correspondante
    @chosen = @dish.availabilities.find_by(available_datetime: @chosen_shift)
    @chosen_availability = format_datetime(@chosen_shift)
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      redirect_to dishes_path
    else
      render :new
    end
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :description, :gluten_free, :vegetarian, :bio, :photo)
  end

  def format_datetime(datetime)
    datetime.hour == 12 ? lunch = "Midi" : lunch = "Soir"
    return "#{datetime.day}/#{datetime.month}/#{datetime.year}, #{lunch}"
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_action :find_order, only: [:show, :update, :destroy]

def index
  @orders = Order.joins(:user)
                 .where("user_id = ?", current_user.id)
end

def create
  @order = Order.new(order_params)
  @order.user = current_user
  @dish = Availability.find(params[:order][:availability_id]).dish
    if @order.save
      redirect_to orders_path
      # verifier la route exacte pour la redirection apres save order
    else
      render 'dishes/show'
    end
end


private

  def find_orders
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:portions, :review_description, :review_rating, :availability_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dishes/index.html.erb
<div class="search-bar">
  <div class="container">
    <%= simple_form_for :search, url: dishes_path, :method => :get, :class => "form-inline" do |f| %>
      <div class="row">
        <div class="col-lg-2">
          <%= f.input :date, input_html: { id: "mydatepicker", value: @searched_date }, required: false, label: false %>
        </div>
        <div class="col-lg-2">
          <%= f.input :slot, collection: ["Midi", "Soir"], selected: @searched_slot, required: false, label: false %>
        </div>
        <div class="col-lg-2">
          <%= f.input :address, as: :string, input_html: { id: "address", value: @searched_address }, required: false, autocomplete: "off", label: false, placeholder: "Address" %>
        </div>
        <div class="col-lg-2">
          <%= f.input :portions, collection: 1..@max_results_portions, selected: @searched_portions || 1, label: false %>
        </div>
        <div class="col-lg-2">
          <%= f.input :types, collection: ['Bio', 'Sans gluten', 'Végétarien'], selected: @searched_types, input_html: { }, label: false %>
        </div>
        <div class="col-lg-2">
          <%= f.submit "Search", class: "btn btn-primary search-index" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <div class="row">
        <% @dishes.each do |dish|%>
          <div class="col-lg-6 col-xs-12">
            <%= link_to dish_path(dish.id, shift: @datetime) do %>
              <div class="card-result" style="background-image:url('<%= cl_image_path dish.photo.path%>')">
                <div class="mini-profile">
                  <%= cl_image_tag dish.user.photo.path, class: "avatar-large" %>
                  <div class="rating">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                  </div>
                </div>
                <div class="card-content">
                  <p class="card-dish-title"><%= dish.name %></p>
                  <div class="price-card"><%= dish.price %> €</div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4">
      <div id="map" class="map"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
        else {
          handler.getMap().setZoom(16);
        }
      });
      $("#mydatepicker").datepicker('setDate', '<%= @searched_date %>');
    });
  </script>
<% end %>

app/views/dishes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New dish</h1>

      <%= simple_form_for(@dish) do |f| %>
        <%= f.input :name, label: 'Add New Dish', required: true, placeholder: "new dish" %>
        <%= f.input :description, label: 'Description' %>
        <%= f.input :gluten_free, inline_label: 'it is Gluten Free' %>
        <%= f.input :vegetarian, inline_label: 'it is vegetarian' %>
        <%= f.input :bio, inline_label: 'it is bio' %>
        <%= f.input :photo, as: :attachinary %>
        <%= f.button :submit, class: "btn btn-primary"  %>
      <% end %>

    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="chosen-availability">Date sélectionnée : <%=@chosen_availability%></div>


<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 show-card-wrapper">
        <div class="show-card" style="background-image:url('<%= cl_image_path @dish.photo.path%>')">
          <%= cl_image_tag @dish.user.photo.path, class: "dish-user-photo avatar-large" %>
          <%= "#{@dish.user.firstname} #{@dish.user.lastname[0]}. vous propose :" %>
          <div class="dish-description">
            <div class="dish-desc-mini">
              <%= @dish.name %>
              <%= @dish.description %>
            </div>
            <div class="price-card">
            <%= @dish.price.to_s + " €" %>
              <% if @dish.bio == true %>
            <span class="label label-success">Bio</span>
          <% end %>

          <% if @dish.gluten_free == true %>
            <span class="label label-success">Gluten</span>
          <% end %>
          <% if @dish.vegetarian == true %>
            <span class="label label-success">Vegetarian</span>
          <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="side-choice">
          <%= simple_form_for :order, url: orders_path, :method => :post do |f| %>
            <%= f.input :availability_id, as: :hidden, input_html: { value: @chosen.id } %>
            <%= f.input :portions, collection: 1..@chosen.portions %>
            <h4><div id="order-amount"><%=@dish.price%> €</div></h4>
            <%= f.button :submit, value: "Place order", class: "btn btn-primary"  %>
          <% end %>
        </div>
      </div>
  </div>
</div>
<% content_for(:after_js) do %>
  <script>
    $('#order_portions').change(function (){
      var portions = $('#order_portions option:selected').text();
      var dprice = <%= @dish.price %>;
      var amount = String(portions * dprice) + " €";
      $("#order-amount").text(amount);
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="body-content">
       <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    Votre commande est confirmée
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <h2 class="text-center">vos précédentes commandes</h2>
      <p>
        <% @orders.each do |order| %>
          <ul>
            <li>
              <%= "#{order.availability.available_datetime.strftime('%d/%m/%Y')} : #{order.availability.dish.name} (#{order.portions}) - " %>
              <small><%= link_to "laisser une évaluation", root_path %></small>
            </li>
          </ul>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">New Order</h1>

      <%= simple_form_for(@order) do |f| %>
        <%= f.input :portions, label: 'Add New order', required: true, collection: 1..5 %>
        <%= f.input :review_description, label: 'Description' %>
        <%= f.input :review_rating, label: 'Rating' %>
        <%= f.button :submit, class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-wrapper">
  <div class="overlay">
  <div class="slogan">
    <h1>
      LunchBox
    </h1>
    <p>Votre repas maison à 2 pas de chez vous</p>
  </div>
    <div class="form-card">
      <div class="container">
        <div class="row form-home">
          <%= simple_form_for :search, url: dishes_path, :method => :get, :class => "form-inline" do |f| %>
            <div class="col-lg-3 col-sm-6 form-group">
              <%= f.input :date, input_html: {id: "mydatepicker"}, required: false %>
            </div>
            <div class="col-lg-3 col-sm-6 form-group">
              <% Time.now.hour > 14 ? slot = "Soir" : slot = "Midi" %>
              <%= f.input :slot, collection: ["Midi", "Soir"], selected: slot, required: false %>
            </div>
            <div class="col-lg-3 col-sm-6 form-group">
              <%= f.input :address, as: :string, input_html: {id: "address"}, required: false, autocomplete: "off" %>
            </div>
            <div class="col-lg-3 col-sm-6 form-group">
              <%= f.submit "Search", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= content_for(:after_js) do %>
  <script>
    function initialize() {
      var input = document.getElementById('address');
      var autocomplete = new google.maps.places.Autocomplete(input);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    $("#mydatepicker").datepicker('setDate', new Date());
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-lunchbox">
  <div class="logo-name">
    <%= link_to root_path, class: "footer-img" do %>
      <%= image_tag "logo-svg-colors/hot-kitchen-pot-black.svg" %>
    <% end %>
    <p class="navbar-wagon-link navbar-wagon-item footer-cpy-name"> LunchBox </p>
  </div>
  <div class="footer-data">
    <ul>
      <li class="navbar-wagon-item navbar-wagon-link footer-link"> Terms & conditions </li>
      <li class="navbar-wagon-item navbar-wagon-link footer-link"> Contact </li>
      <li class="navbar-wagon-item navbar-wagon-link footer-link"> FAQ </li>
    </ul>
  </div>
  <div class="social-links">
    <i class="fa fa-twitter navbar-wagon-item navbar-wagon-link footer-link" aria-hidden="true"></i>
    <i class="fa fa-facebook navbar-wagon-item navbar-wagon-link footer-link" aria-hidden="true"></i>
    <i class="fa fa-instagram navbar-wagon-item navbar-wagon-link footer-link" aria-hidden="true"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo-name">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-svg-colors/hot-kitchen-pot-coral.svg" %>
    <% end %>
    <p class="navbar-wagon-link company-name"> LunchBox </p>
  </div>




  <!-- Different navigation if login or not -->
  <% if user_signed_in? %>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

  <% else %>

    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".about", default: "About"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".help", default: "Help"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Log in</a></li>
          <li><a href="#">Sign up</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Help</a></li>
        </ul>
      </div>
    </div>
  <% end %>


</div>